{{- if .Values.namespace }}
{{- if gt (len .Values.namespace.labels) 0 }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "modx.labelnamespace.fullname" . }}
{{ include "modx.namespace" . | indent 2 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade #post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "-10"
  labels:
  {{- include "modx.labelnamespace.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "modx.labelnamespace.serviceAccountName" . }}
      containers:
      - name: label-namespace
        {{- if .Values.kubectl.image.digest }}
        image: "{{ .Values.kubectl.image.repository }}@{{ .Values.kubectl.image.digest }}"
        {{- else if .Values.kubectl.image.tag }}
        image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
        {{- else }}
        image: "{{ .Values.kubectl.image.repository }}:{{ template "chart.KubernetesVersion" . }}"
        {{- end }}
        {{- with .Values.labelnamespace.containerSecurityContext }}
        securityContext:
        {{- toYaml . | nindent 12 }}
        {{- end }}
        command:
        - /bin/sh
        - -c
        - |
          {{- range .Values.namespace.labels }}
          kubectl label namespace {{ $.Release.Namespace }} {{ .key }}={{ .value }}
          {{- end }}
      restartPolicy: Never
  backoffLimit: 3
{{- end }}
{{- end }}