{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "modx-chart.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: {{ include "modx-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "modx-chart.chart" . }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

{{- end }}