apiVersion: v1
kind: Service
metadata:
  name: {{ include "modx-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "modx-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "modx-chart.chart" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP
  selector:
    name: modx-chart
    app.kubernetes.io/name: {{ include "modx-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
