apiVersion: v1
kind: Service
metadata:
  name: {{ include "modx-chart.fullname" . }}
  labels:
    {{- include "modx-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP
  selector:
    {{- include "modx-chart.selectorLabels" . | nindent 4 }}
