apiVersion: v1
kind: Secret
metadata:
  name: modx-secret
  namespace: ${SITE_NAME}
type: Opaque
data:
  # Encoded value: echo -n 'rootpass'|base64
  mariadb-root-password: cm9vdHBhc3M=
  modx-cms-admin-pass: cm9vdHBhc3M=