apiVersion: v1
kind: Secret
metadata:
  name: ${SITE_NAME}-secret
  namespace: ${SITE_NAME}
type: Opaque
data:
  # Encoded value: echo -n 'rootpass'|base64
  mariadb-modx-password: eEIzZXEwVE5XR1RJ
  modx-cms-admin-pass: YWRtaW4=