kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${SITE_NAME}-pv-claim
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tkgs-legacy-web-storage-policy
  resources:
    requests:
      storage: 2Gi
