apiVersion: v1
kind: Service
metadata:
  name: kapeo-sa
  labels:
    name: kapeo-sa
spec:
  selector:
    name: kapeo-sa
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
  