apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
  namespace: ${BRANCH_NAME}
spec:
  selector:
    name: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  type: LoadBalancer
  