apiVersion: v1
kind: Service
metadata:
  name: ${BRANCH_ID}-nginx
  labels:
    name: nginx
  namespace: ${NAMESPACE}
#spec:
#  type: ClusterIP
#  selector:
#    name: php-fpm
#  ports:
#    - port: 80
#      targetPort: 80

spec:
  selector:
    name: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer

  