apiVersion: v1
kind: Service
metadata:
  name: ${BRANCH_ID}-php-fpm
  labels:
    name: php-fpm
  namespace: ${NAMESPACE}
spec:
  type: ClusterIP
  selector:
    name: php-fpm
  ports:
    - port: 9000
      targetPort: 9000