apiVersion: v1
kind: ConfigMap
metadata:
  name: ${BRANCH_ID}-nginx-certs
  namespace: ${NAMESPACE}
data:
  server.crt: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  server.key: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----