apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  labels:
    name: php-fpm
  namespace: ${BRANCH_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: php-fpm
  template:
    metadata:
      labels:
        name: php-fpm
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      #securityContext:
      #  fsGroup: 1001
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: php-fpm-pv
          persistentVolumeClaim:
            claimName: ${BRANCH_ID}-pv-claim
      containers:
        - name: php-fpm
          image: artyomyudin/php-fpm:5.3.29
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: php-fpm-pv
              mountPath: /app
