apiVersion: v1
kind: Namespace
metadata:
  name: ${BRANCH_NAME}
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline