kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${BRANCH_ID}-storage
  namespace: ${BRANCH_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tkgs-legacy-web-storage-policy
  resources:
    requests:
      storage: 1Gi
