kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-storage
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tkgs-legacy-web-storage-policy
  resources:
    requests:
      storage: 0.5Gi
