apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      #securityContext:
      #  fsGroup: 1001
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nginx-pv
          persistentVolumeClaim:
            claimName: ${SITE_NAME}-pv-claim
        - name: ${SITE_NAME}-nginx-certs
          configMap:
            name: masterutm-cert # place ConfigMap `nginx-conf` on /etc/nginx
            items:
              - key: server.key
                path: server.key # dig directory
              - key: server.crt
                path: server.crt # dig directory
      containers:
        - name: nginx
          image: artyomyudin/nginx:1.22.1-9.1
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
              protocol: TCP
          env:
            - name: SITES
              value: ${DOMAIN}
            - name: TZ
              value: "Europe/Moscow"
            - name: NGINX_SKIP_SAMPLE_CERTS
              value: "true"
            - name: ENDPOINT
              value: "php-fpm"
            - name: PROXY
              value: "false"
          volumeMounts:
            - name: nginx-pv
              mountPath: /app
            - name: ${SITE_NAME}-nginx-certs
              mountPath: /etc/nginx/certs/ # mount nginx-conf volumn to /etc/nginx
              readOnly: true

      