apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
  namespace: ${NAMESPACE}
spec:
  selector:
    name: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 172.30.200.7
  