apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    name: php-fpm
  namespace: ${SITE_NAME}
spec:
  type: ClusterIP
  selector:
    name: php-fpm
  ports:
    - port: 9000
      targetPort: 9000