kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pv-claim
  namespace: mariadb
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: tkgs-legacy-web-storage-policy