apiVersion: apps/v1
kind: Deployment
metadata:
  name: r48
  labels:
    name: r48
spec:
  replicas: 1
  selector:
    matchLabels:
      name: r48
  template:
    metadata:
      labels:
        name: r48
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nginx-certs
          persistentVolumeClaim:
            claimName: r48-storage
      containers:
        - name: r48
          image: hanna.center-inform.ru/kapeo-sa/kapeo-sa-nginx:latest
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: nginx-certs
              mountPath: /bitnami/certs/
      imagePullSecrets:
        - name: regsecret
      