apiVersion: v1
kind: Service
metadata:
  labels:
    name: mariadb
  name: mariadb
  namespace: ${NAMESPACE}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mariadb