{{- if .Values.serviceAccounts.labelnamespace.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "modx.labelnamespace.labels" $ | nindent 4 }}
  name: {{ template "modx.labelnamespace.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy":  before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-10"
{{- end -}}