{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
      {{- include "modx.labelnamespace.labels" $ | nindent 4 }}
  name: {{ template "modx.labelnamespace.fullname" $ }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade #post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed #hook-succeeded
    "helm.sh/hook-weight": "-10"
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs:     ["get", "patch"]
  resourceNames: [{{ .Release.Namespace }}]
{{- end }}