{{- if .Values.serviceAccounts.labelnamespace.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
      {{- include "modx.labelnamespace.labels" $ | nindent 4 }}
  name: {{ template "modx.labelnamespace.serviceAccountName" . }}
{{ include "modx.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.serviceAccounts.labelnamespace.annotations | indent 4 }}
{{- end -}}