{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
      {{- include "modx.labelnamespace.labels" $ | nindent 4 }}
  name: {{ template "modx.labelnamespace.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "patch", "update"]
  resourceNames:
  - {{ template "modx.labelnamespace.fullname" . }}
{{- end }}