{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
      {{- include "modx.php-fpm.labels" $ | nindent 4 }}
  name: {{ template "modx.php-fpm.fullname" . }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "modx.php-fpm.fullname" . }}
{{- end }}