{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "modx.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ include "modx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "modx.chart" . }}
{{- with .Values.serviceAccount.labels }}
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.serviceAccount.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
{{- end }}
